curl -X GET https://api.cloud.com/cvad/manage/me \
     -H "Accept: application/json" \
     -H "Content-Type: application/json; charset=utf-8" \
     -H "Authorization: CWSAuth bearer=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjNWEyNTU5NC1mZTA1LTRmMDItYWM0My1iNjhhY2ExMDUyMTQiLCJ1c2VyX2lkIjoiT0lEOi9jaXRyaXgvYzVhMjU1OTQtZmUwNS00ZjAyLWFjNDMtYjY4YWNhMTA1MjE0IiwiZGlzcGxheU5hbWUiOiJXQVoiLCJuYW1lIjoiV0FaIiwiZW1haWwiOiIiLCJhbXIiOiJbXCJjbGllbnRcIl0iLCJpZHAiOiJjaXRyaXhzdHMiLCJjdXN0b21lcnMiOiJbe1wiQ3VzdG9tZXJJZFwiOlwiZXljMDJtYmszMWxpXCIsXCJHZW9cIjpcIkVVXCJ9XSIsImRpc2NvdmVyeSI6IntcIklzc3VlclwiOlwiaHR0cHM6Ly90cnVzdC1ldS5jaXRyaXh3b3Jrc3BhY2VzYXBpLm5ldFwifSIsImN0eF9hdXRoX2FsaWFzIjoiNjEzOTBkNTAtMGE5MC00ZmRmLWFjMzEtZDRhZGUxNGE4NDU3IiwiY3R4X3VzZXIiOiJ7XCJPaWRcIjpcIk9JRDovY2l0cml4L2M1YTI1NTk0LWZlMDUtNGYwMi1hYzQzLWI2OGFjYTEwNTIxNFwifSIsIm5iZiI6MTczODY2NDg3NSwiZXhwIjoxNzM4NjY4NDc1LCJpYXQiOjE3Mzg2NjQ4NzUsImlzcyI6ImN3cyJ9.H1v6HAe_TciJdfJy4oBHGf1Iv54hW18ocoMKJot8EOzGN-H6ruIeHzVMJJES4yxrXVAwqZWXfEQctfxxxxxxxxxxxi8Ho6YtlkKor6KH9yZmn0mvIGSqCry-4FkabJ3uA3UTPOCJxHyn-fD4ewDz3i7tDn_4KtSsNgfw7Xpg82LdJSyPiADM6gg" \
     -H "Citrix-CustomerId: xxx2mxxx1li"

